export const THEME_KEYS = {
  POWER_RANGERS: "POWER_RANGERS",
  SANDY_BEACH: "SANDY_BEACH",
  PINKY_CAT: "PINKY_CAT",
  GIPSY_KING: "GIPSY_KING",
  SUNNY_NIGHT: "SUNNY_NIGHT",
  PINK_WEREWOLF: "PINK_WEREWOLF",
  SMOKY_WINTER: "SMOKY_WINTER",
};

export const THEME_ACTION_TYPES = {
  SET_THEME: "SET_THEME",
};
