export const PREFERENCES_ACTION_TYPES = {
    SET_GOAL: "SET_GOAL",
    SET_DURATION: "SET_DURATION",
    SET_DIET: "SET_DIET",
    SET_WEIGHT: "SET_WEIGHT",
    SET_RESTRICTIONS: "SET_RESTRICTIONS"
}